repos:
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.16.0" # replace with latest tag on GitHub
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==22.12.0
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0 # replace with latest tag on GitHub
    hooks:
    - id: markdownlint # https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
      args:
        - --fix